/**
 * Localized copy for everything the user sees that is NOT generated by the LLM.
 * The mentor's own replies are localized by a system-prompt directive (see
 * llm/prompts.ts); this catalog covers the deterministic strings: onboarding,
 * binding, ops messages, no-LLM metric lookups, graceful exits, guardrail
 * deflections, and the deterministic report fallback.
 *
 * Each entry is either a constant string or a small pure function over
 * already-formatted, locale-neutral values (currency/percent strings come
 * pre-formatted from metrics.display.*). Branch selection (which variant,
 * singular/plural) stays in the callers; only the wording lives here.
 *
 * The English (`en`) entries reproduce the original hard-coded copy verbatim.
 */
import type { Language } from './languages.js';

export interface LookupWinRate {
  readonly period: string;
  readonly winRate: string;
  readonly wins: number;
  readonly losses: number;
}

export interface Strings {
  // ── Onboarding / binding ───────────────────────────────────────────────────
  readonly welcome: string;
  readonly chooseLanguage: string;
  readonly languageSet: (native: string) => string;
  readonly bindSuccess: string;
  readonly bindAlready: string;
  readonly bindExpired: string;
  readonly bindInvalid: string;
  readonly bindConflict: string;
  readonly bindError: string;
  readonly accountLinked: (crmClientId: string) => string;

  // ── Ops / system ───────────────────────────────────────────────────────────
  readonly unbound: string;
  readonly holding: string;
  readonly throttle: string;
  readonly handoff: string;
  readonly cooldown: string;
  readonly sttFailed: string;
  readonly dataLoadFailed: string;

  // ── Period phrases ("this week" / "this day"), and report adjectives ────────
  readonly periodDay: string;
  readonly periodWeek: string;
  readonly periodDaily: string;
  readonly periodWeekly: string;
  readonly singleInstrument: string;

  // ── No-LLM metric lookups ───────────────────────────────────────────────────
  readonly lookupDrawdown: (p: { period: string; dd: string; ddPct: string }) => string;
  readonly lookupWinRate: (p: LookupWinRate) => string;
  readonly lookupWinRateNone: (p: { period: string }) => string;
  readonly lookupTradeCount: (p: { period: string; n: number }) => string;
  readonly lookupPnl: (p: { period: string; pnl: string }) => string;
  readonly lookupOpenPositions: (p: { n: number; openPnL: string; margin: string }) => string;
  readonly lookupBestTrade: (p: { period: string; best: string }) => string;
  readonly lookupWorstTrade: (p: { period: string; worst: string }) => string;
  readonly lookupExposure: (p: { pct: string; symbol: string }) => string;
  readonly lookupExposureNone: string;

  // ── Graceful exit ───────────────────────────────────────────────────────────
  readonly exitV0: string;
  readonly exitV1: (p: { homework: string }) => string;
  readonly exitV2: (p: { recap: string }) => string;
  readonly homeworkWeekend: string;
  readonly homeworkOverleverage: string;
  readonly homeworkRevenge: string;
  readonly homeworkDefault: string;
  readonly recapMetrics: (p: { n: number; winRate: string; pnl: string; period: string }) => string;
  readonly recapDefault: string;

  // ── Guardrail deflection ────────────────────────────────────────────────────
  readonly deflectionExposureFragSymbol: (p: { pct: string; symbol: string }) => string;
  readonly deflectionExposureFragGeneric: (p: { pct: string }) => string;
  readonly deflectionExposure: (p: { exposure: string; margin: string }) => string;
  readonly deflectionHistory: (p: { period: string; winRate: string; n: number; pnl: string }) => string;
  readonly deflectionGeneric: string;

  // ── Deterministic report fallback ───────────────────────────────────────────
  readonly report: {
    readonly title: (p: { period: string; from: string; to: string }) => string;
    readonly netPnl: (p: { v: string }) => string;
    readonly winRate: (p: { v: string; record: string }) => string;
    readonly bestTrade: (p: { v: string }) => string;
    readonly worstTrade: (p: { v: string }) => string;
    readonly avgHoldDrawdown: (p: { avgHold: string; dd: string; ddPct: string }) => string;
    readonly openRisk: (p: { n: string; openPnL: string; margin: string }) => string;
    readonly stoodOut: string;
  };
}

// ── English (canonical — matches the original hard-coded copy) ─────────────────
const en: Strings = {
  welcome:
    '👋 Welcome to Milele Prime AI.\n\n' +
    'To link your account, tap the Connect button in your Milele dashboard.',
  chooseLanguage: '🌍 Which language would you like to chat in? Tap one below.',
  languageSet: (native) =>
    `✅ Language set to ${native}. I'll chat with you in ${native} from now on. You can change it anytime with /language.`,
  bindSuccess:
    '✅ Your Telegram is now linked to your Milele account. You can also enable voice and daily reports from your dashboard.',
  bindAlready: '✅ Your account is already linked — you’re all set.',
  bindExpired:
    '⏳ That connect link has expired. Please open a fresh Connect link from your Milele dashboard.',
  bindInvalid: '⚠️ That connect link is invalid. Please use the Connect button in your Milele dashboard.',
  bindConflict: '⚠️ This account is already linked to a different profile. Please contact support.',
  bindError: '⚠️ Something went wrong linking your account. Please try again shortly.',
  accountLinked: (id) => `🔗 Linked to client ${id}. Account features arrive in a later phase.`,

  unbound: 'Tap the Connect button in your Milele dashboard to link your account.',
  holding: "I'm taking a quick break — back shortly. Your message is safe; ping me again in a bit.",
  throttle: 'Give me a sec — you’re sending those faster than I can think. I’ll catch up in a moment.',
  handoff:
    "Thanks for flagging this — I'm connecting you with a member of the Milele team who can help you directly. They'll follow up shortly.",
  cooldown:
    "I'm still catching my breath from our last chat — give me a few minutes and message me again. I'll be fresh and ready.",
  sttFailed: "I couldn't make out that voice note — mind typing it instead?",
  dataLoadFailed:
    "I'm having trouble loading your account data right now — try me again in a few minutes.",

  periodDay: 'this day',
  periodWeek: 'this week',
  periodDaily: 'daily',
  periodWeekly: 'weekly',
  singleInstrument: 'a single instrument',

  lookupDrawdown: ({ period, dd, ddPct }) =>
    `Your max drawdown ${period} was ${dd} (${ddPct} of balance).`,
  lookupWinRate: ({ period, winRate, wins, losses }) =>
    `Your win rate ${period} is ${winRate} — ${wins} wins, ${losses} losses.`,
  lookupWinRateNone: ({ period }) =>
    `You have no closed trades ${period} yet, so there's no win rate to report.`,
  lookupTradeCount: ({ period, n }) =>
    `You closed ${n} ${n === 1 ? 'trade' : 'trades'} ${period}.`,
  lookupPnl: ({ period, pnl }) => `Your net result ${period} is ${pnl}.`,
  lookupOpenPositions: ({ n, openPnL, margin }) =>
    `You currently have ${n} open ${n === 1 ? 'position' : 'positions'}, ${openPnL} unrealized, with margin at ${margin} of equity.`,
  lookupBestTrade: ({ period, best }) => `Your best trade ${period} was ${best}.`,
  lookupWorstTrade: ({ period, worst }) => `Your worst trade ${period} was ${worst}.`,
  lookupExposure: ({ pct, symbol }) => `${pct} of your open exposure is in ${symbol}.`,
  lookupExposureNone: 'You have no open positions right now.',

  exitV0:
    "I've gotta get back to watching the charts — but think on what we covered. Message me anytime.",
  exitV1: ({ homework }) =>
    `Markets don't sleep, so I'm back to the screens. Homework: ${homework}. Talk soon.`,
  exitV2: ({ recap }) => `Stepping away to keep an eye on things. Quick recap: ${recap} I'm around later.`,
  homeworkWeekend: 'review how your weekend holds are affecting your results',
  homeworkOverleverage: 'look at your margin usage relative to your account size',
  homeworkRevenge: 'notice the trades you open right after a loss',
  homeworkDefault: 'review your own numbers before your next session',
  recapMetrics: ({ n, winRate, pnl, period }) =>
    `${n} trades, ${winRate} win rate, ${pnl} net ${period}.`,
  recapDefault: 'we focused on your habits and your current exposure.',

  deflectionExposureFragSymbol: ({ pct, symbol }) =>
    `${pct} of your current open risk is concentrated in ${symbol}`,
  deflectionExposureFragGeneric: ({ pct }) =>
    `${pct} of your current open risk sits in a single instrument`,
  deflectionExposure: ({ exposure, margin }) =>
    "I can't make market calls, price predictions, or buy/sell/hold recommendations — that's not something I'll ever do. " +
    `What I can do is help you think about your own exposure: ${exposure}, ` +
    `and your margin is using ${margin} of your equity. ` +
    'Want to talk through how that sits against your account size?',
  deflectionHistory: ({ period, winRate, n, pnl }) =>
    "I can't make market calls, price predictions, or buy/sell/hold recommendations — that's not something I'll ever do. " +
    `What I can do is help you reflect on your own history — for example, your win rate ${period} was ${winRate} across ` +
    `${n} trades, with a net result of ${pnl}. Want to dig into what's working and what isn't?`,
  deflectionGeneric:
    "I can't make market calls, price predictions, or buy/sell/hold recommendations — that's not something I'll ever do. " +
    'What I can do is help you understand your own positions, risk, and habits. What would you like to look at?',

  report: {
    title: ({ period, from, to }) => `Your ${period} summary (${from} → ${to})`,
    netPnl: ({ v }) => `Net P&L: ${v}`,
    winRate: ({ v, record }) => `Win rate: ${v} (${record})`,
    bestTrade: ({ v }) => `Best trade: ${v}`,
    worstTrade: ({ v }) => `Worst trade: ${v}`,
    avgHoldDrawdown: ({ avgHold, dd, ddPct }) =>
      `Avg hold: ${avgHold}  |  Max drawdown: ${dd} (${ddPct})`,
    openRisk: ({ n, openPnL, margin }) =>
      `Open risk: ${n} position(s), ${openPnL} unrealized, margin ${margin}`,
    stoodOut: 'What stood out:',
  },
};

// ── Urdu (اردو) ────────────────────────────────────────────────────────────────
const ur: Strings = {
  welcome:
    '👋 Milele Prime AI میں خوش آمدید۔\n\n' +
    'اپنا اکاؤنٹ لنک کرنے کے لیے، اپنے Milele ڈیش بورڈ میں Connect بٹن دبائیں۔',
  chooseLanguage: '🌍 آپ کس زبان میں بات کرنا چاہیں گے؟ نیچے سے ایک منتخب کریں۔',
  languageSet: (native) =>
    `✅ زبان ${native} پر سیٹ کر دی گئی ہے۔ اب سے میں آپ سے ${native} میں بات کروں گا۔ آپ اسے /language کے ذریعے کبھی بھی بدل سکتے ہیں۔`,
  bindSuccess:
    '✅ آپ کا ٹیلیگرام اب آپ کے Milele اکاؤنٹ سے منسلک ہو گیا ہے۔ آپ اپنے ڈیش بورڈ سے وائس اور روزانہ رپورٹس بھی فعال کر سکتے ہیں۔',
  bindAlready: '✅ آپ کا اکاؤنٹ پہلے ہی منسلک ہے — سب تیار ہے۔',
  bindExpired:
    '⏳ وہ کنیکٹ لنک ختم ہو چکا ہے۔ براہ کرم اپنے Milele ڈیش بورڈ سے نیا Connect لنک کھولیں۔',
  bindInvalid: '⚠️ وہ کنیکٹ لنک غلط ہے۔ براہ کرم اپنے Milele ڈیش بورڈ میں Connect بٹن استعمال کریں۔',
  bindConflict: '⚠️ یہ اکاؤنٹ پہلے ہی کسی دوسرے پروفائل سے منسلک ہے۔ براہ کرم سپورٹ سے رابطہ کریں۔',
  bindError: '⚠️ آپ کا اکاؤنٹ منسلک کرنے میں کچھ خرابی ہوئی۔ براہ کرم تھوڑی دیر بعد دوبارہ کوشش کریں۔',
  accountLinked: (id) => `🔗 کلائنٹ ${id} سے منسلک۔ اکاؤنٹ کی خصوصیات ایک بعد کے مرحلے میں آئیں گی۔`,

  unbound: 'اپنا اکاؤنٹ لنک کرنے کے لیے اپنے Milele ڈیش بورڈ میں Connect بٹن دبائیں۔',
  holding: 'میں تھوڑی دیر کے لیے وقفہ لے رہا ہوں — جلد واپس آتا ہوں۔ آپ کا پیغام محفوظ ہے؛ تھوڑی دیر بعد دوبارہ پیغام بھیجیں۔',
  throttle: 'ذرا ایک لمحہ دیں — آپ اتنی تیزی سے بھیج رہے ہیں کہ میں سوچ بھی نہیں پا رہا۔ میں ابھی پکڑ لیتا ہوں۔',
  handoff:
    'اسے بتانے کا شکریہ — میں آپ کو Milele ٹیم کے ایک رکن سے ملا رہا ہوں جو آپ کی براہ راست مدد کر سکتا ہے۔ وہ جلد آپ سے رابطہ کریں گے۔',
  cooldown:
    'میں ابھی اپنی پچھلی گفتگو سے سانس لے رہا ہوں — چند منٹ دیں اور دوبارہ پیغام بھیجیں۔ میں تازہ دم اور تیار ہوں گا۔',
  sttFailed: 'میں وہ وائس نوٹ سمجھ نہیں سکا — کیا آپ اسے ٹائپ کر کے بھیج سکتے ہیں؟',
  dataLoadFailed:
    'اس وقت مجھے آپ کے اکاؤنٹ کا ڈیٹا لوڈ کرنے میں دشواری ہو رہی ہے — چند منٹ بعد دوبارہ کوشش کریں۔',

  periodDay: 'اس دن',
  periodWeek: 'اس ہفتے',
  periodDaily: 'روزانہ',
  periodWeekly: 'ہفتہ وار',
  singleInstrument: 'ایک ہی انسٹرومنٹ',

  lookupDrawdown: ({ period, dd, ddPct }) =>
    `${period} آپ کا زیادہ سے زیادہ ڈرا ڈاؤن ${dd} تھا (بیلنس کا ${ddPct})۔`,
  lookupWinRate: ({ period, winRate, wins, losses }) =>
    `${period} آپ کی جیت کی شرح ${winRate} ہے — ${wins} جیت، ${losses} ہار۔`,
  lookupWinRateNone: ({ period }) =>
    `${period} آپ کے ابھی کوئی بند شدہ ٹریڈز نہیں ہیں، اس لیے جیت کی شرح بتانے کو کچھ نہیں۔`,
  lookupTradeCount: ({ period, n }) => `${period} آپ نے ${n} ٹریڈز بند کیے۔`,
  lookupPnl: ({ period, pnl }) => `${period} آپ کا خالص نتیجہ ${pnl} ہے۔`,
  lookupOpenPositions: ({ n, openPnL, margin }) =>
    `اس وقت آپ کے ${n} کھلے پوزیشنز ہیں، ${openPnL} غیر حاصل شدہ، اور مارجن ایکویٹی کا ${margin} استعمال کر رہا ہے۔`,
  lookupBestTrade: ({ period, best }) => `${period} آپ کا بہترین ٹریڈ ${best} تھا۔`,
  lookupWorstTrade: ({ period, worst }) => `${period} آپ کا بدترین ٹریڈ ${worst} تھا۔`,
  lookupExposure: ({ pct, symbol }) => `آپ کے کھلے ایکسپوژر کا ${pct} ${symbol} میں ہے۔`,
  lookupExposureNone: 'اس وقت آپ کے کوئی کھلے پوزیشنز نہیں ہیں۔',

  exitV0:
    'مجھے واپس چارٹس دیکھنے جانا ہے — لیکن جو ہم نے بات کی اس پر غور کریں۔ جب چاہیں پیغام دیں۔',
  exitV1: ({ homework }) =>
    `مارکیٹس سوتی نہیں، تو میں واپس اسکرینوں پر ہوں۔ ہوم ورک: ${homework}۔ جلد بات کرتے ہیں۔`,
  exitV2: ({ recap }) => `تھوڑی دیر کے لیے جا رہا ہوں تاکہ نظر رکھ سکوں۔ مختصر خلاصہ: ${recap} میں بعد میں موجود ہوں۔`,
  homeworkWeekend: 'دیکھیں کہ ہفتے کے آخر میں آپ کے پوزیشنز رکھنا آپ کے نتائج پر کیسے اثر ڈال رہا ہے',
  homeworkOverleverage: 'اپنے اکاؤنٹ کے سائز کے مقابلے میں اپنے مارجن کے استعمال کو دیکھیں',
  homeworkRevenge: 'ان ٹریڈز پر غور کریں جو آپ نقصان کے فوراً بعد کھولتے ہیں',
  homeworkDefault: 'اپنے اگلے سیشن سے پہلے اپنے اعداد و شمار کا جائزہ لیں',
  recapMetrics: ({ n, winRate, pnl, period }) =>
    `${n} ٹریڈز، ${winRate} جیت کی شرح، ${pnl} خالص ${period}۔`,
  recapDefault: 'ہم نے آپ کی عادات اور آپ کے موجودہ ایکسپوژر پر توجہ دی۔',

  deflectionExposureFragSymbol: ({ pct, symbol }) =>
    `آپ کے موجودہ کھلے رسک کا ${pct} ${symbol} میں مرتکز ہے`,
  deflectionExposureFragGeneric: ({ pct }) =>
    `آپ کے موجودہ کھلے رسک کا ${pct} ایک ہی انسٹرومنٹ میں ہے`,
  deflectionExposure: ({ exposure, margin }) =>
    'میں مارکیٹ کی پیش گوئیاں، قیمت کی پیش گوئیاں، یا خریدنے/بیچنے/رکھنے کی سفارشات نہیں کر سکتا — یہ میں کبھی نہیں کروں گا۔ ' +
    `البتہ میں آپ کے اپنے ایکسپوژر کے بارے میں سوچنے میں مدد کر سکتا ہوں: ${exposure}، ` +
    `اور آپ کا مارجن آپ کی ایکویٹی کا ${margin} استعمال کر رہا ہے۔ ` +
    'کیا آپ بات کرنا چاہیں گے کہ یہ آپ کے اکاؤنٹ کے سائز کے مقابلے میں کیسا ہے؟',
  deflectionHistory: ({ period, winRate, n, pnl }) =>
    'میں مارکیٹ کی پیش گوئیاں، قیمت کی پیش گوئیاں، یا خریدنے/بیچنے/رکھنے کی سفارشات نہیں کر سکتا — یہ میں کبھی نہیں کروں گا۔ ' +
    `البتہ میں آپ کی اپنی تاریخ پر غور کرنے میں مدد کر سکتا ہوں — مثلاً، ${period} آپ کی جیت کی شرح ${winRate} تھی ` +
    `${n} ٹریڈز میں، اور خالص نتیجہ ${pnl}۔ کیا ہم دیکھیں کہ کیا کام کر رہا ہے اور کیا نہیں؟`,
  deflectionGeneric:
    'میں مارکیٹ کی پیش گوئیاں، قیمت کی پیش گوئیاں، یا خریدنے/بیچنے/رکھنے کی سفارشات نہیں کر سکتا — یہ میں کبھی نہیں کروں گا۔ ' +
    'البتہ میں آپ کو آپ کے اپنے پوزیشنز، رسک اور عادات سمجھنے میں مدد کر سکتا ہوں۔ آپ کیا دیکھنا چاہیں گے؟',

  report: {
    title: ({ period, from, to }) => `آپ کا ${period} خلاصہ (${from} → ${to})`,
    netPnl: ({ v }) => `خالص منافع/نقصان: ${v}`,
    winRate: ({ v, record }) => `جیت کی شرح: ${v} (${record})`,
    bestTrade: ({ v }) => `بہترین ٹریڈ: ${v}`,
    worstTrade: ({ v }) => `بدترین ٹریڈ: ${v}`,
    avgHoldDrawdown: ({ avgHold, dd, ddPct }) =>
      `اوسط ہولڈ: ${avgHold}  |  زیادہ سے زیادہ ڈرا ڈاؤن: ${dd} (${ddPct})`,
    openRisk: ({ n, openPnL, margin }) =>
      `کھلا رسک: ${n} پوزیشن(ز)، ${openPnL} غیر حاصل شدہ، مارجن ${margin}`,
    stoodOut: 'جو نمایاں رہا:',
  },
};

// ── Hindi (हिन्दी) ─────────────────────────────────────────────────────────────
const hi: Strings = {
  welcome:
    '👋 Milele Prime AI में आपका स्वागत है।\n\n' +
    'अपना खाता लिंक करने के लिए, अपने Milele डैशबोर्ड में Connect बटन दबाएँ।',
  chooseLanguage: '🌍 आप किस भाषा में बात करना चाहेंगे? नीचे से एक चुनें।',
  languageSet: (native) =>
    `✅ भाषा ${native} पर सेट कर दी गई है। अब से मैं आपसे ${native} में बात करूँगा। आप इसे /language से कभी भी बदल सकते हैं।`,
  bindSuccess:
    '✅ आपका Telegram अब आपके Milele खाते से लिंक हो गया है। आप अपने डैशबोर्ड से वॉइस और दैनिक रिपोर्ट भी चालू कर सकते हैं।',
  bindAlready: '✅ आपका खाता पहले से लिंक है — सब तैयार है।',
  bindExpired:
    '⏳ वह कनेक्ट लिंक समाप्त हो चुका है। कृपया अपने Milele डैशबोर्ड से एक नया Connect लिंक खोलें।',
  bindInvalid: '⚠️ वह कनेक्ट लिंक अमान्य है। कृपया अपने Milele डैशबोर्ड में Connect बटन का उपयोग करें।',
  bindConflict: '⚠️ यह खाता पहले से किसी अन्य प्रोफ़ाइल से लिंक है। कृपया सहायता से संपर्क करें।',
  bindError: '⚠️ आपका खाता लिंक करने में कुछ गड़बड़ हुई। कृपया थोड़ी देर बाद फिर कोशिश करें।',
  accountLinked: (id) => `🔗 क्लाइंट ${id} से लिंक। खाता सुविधाएँ बाद के चरण में आएँगी।`,

  unbound: 'अपना खाता लिंक करने के लिए अपने Milele डैशबोर्ड में Connect बटन दबाएँ।',
  holding: 'मैं थोड़ा ब्रेक ले रहा हूँ — जल्द वापस आता हूँ। आपका संदेश सुरक्षित है; थोड़ी देर बाद फिर संदेश भेजें।',
  throttle: 'ज़रा एक पल दें — आप इतनी तेज़ी से भेज रहे हैं कि मैं सोच भी नहीं पा रहा। मैं अभी पकड़ लेता हूँ।',
  handoff:
    'इसे बताने के लिए धन्यवाद — मैं आपको Milele टीम के एक सदस्य से जोड़ रहा हूँ जो सीधे आपकी मदद कर सकते हैं। वे जल्द ही आपसे संपर्क करेंगे।',
  cooldown:
    'मैं अभी अपनी पिछली बातचीत से साँस ले रहा हूँ — कुछ मिनट दें और फिर संदेश भेजें। मैं तरोताज़ा और तैयार रहूँगा।',
  sttFailed: 'मैं वह वॉइस नोट समझ नहीं पाया — क्या आप इसे टाइप करके भेज सकते हैं?',
  dataLoadFailed:
    'इस समय मुझे आपके खाते का डेटा लोड करने में परेशानी हो रही है — कुछ मिनट बाद फिर कोशिश करें।',

  periodDay: 'इस दिन',
  periodWeek: 'इस सप्ताह',
  periodDaily: 'दैनिक',
  periodWeekly: 'साप्ताहिक',
  singleInstrument: 'एक ही इंस्ट्रूमेंट',

  lookupDrawdown: ({ period, dd, ddPct }) =>
    `${period} आपका अधिकतम ड्रॉडाउन ${dd} था (बैलेंस का ${ddPct})।`,
  lookupWinRate: ({ period, winRate, wins, losses }) =>
    `${period} आपकी जीत दर ${winRate} है — ${wins} जीत, ${losses} हार।`,
  lookupWinRateNone: ({ period }) =>
    `${period} आपके अभी कोई बंद ट्रेड नहीं हैं, इसलिए बताने के लिए कोई जीत दर नहीं।`,
  lookupTradeCount: ({ period, n }) => `${period} आपने ${n} ट्रेड बंद किए।`,
  lookupPnl: ({ period, pnl }) => `${period} आपका शुद्ध परिणाम ${pnl} है।`,
  lookupOpenPositions: ({ n, openPnL, margin }) =>
    `इस समय आपकी ${n} खुली पोज़िशन हैं, ${openPnL} अवास्तविक, और मार्जिन इक्विटी का ${margin} उपयोग कर रहा है।`,
  lookupBestTrade: ({ period, best }) => `${period} आपका सबसे अच्छा ट्रेड ${best} था।`,
  lookupWorstTrade: ({ period, worst }) => `${period} आपका सबसे खराब ट्रेड ${worst} था।`,
  lookupExposure: ({ pct, symbol }) => `आपके खुले एक्सपोज़र का ${pct} ${symbol} में है।`,
  lookupExposureNone: 'इस समय आपकी कोई खुली पोज़िशन नहीं है।',

  exitV0:
    'मुझे वापस चार्ट देखने जाना है — लेकिन हमने जो बात की उस पर सोचें। जब चाहें संदेश करें।',
  exitV1: ({ homework }) =>
    `बाज़ार सोते नहीं, तो मैं वापस स्क्रीन पर हूँ। होमवर्क: ${homework}। जल्द बात करते हैं।`,
  exitV2: ({ recap }) => `थोड़ी देर के लिए जा रहा हूँ ताकि नज़र रख सकूँ। संक्षेप में: ${recap} मैं बाद में मौजूद हूँ।`,
  homeworkWeekend: 'देखें कि सप्ताहांत में पोज़िशन रखना आपके परिणामों को कैसे प्रभावित कर रहा है',
  homeworkOverleverage: 'अपने खाते के आकार की तुलना में अपने मार्जिन उपयोग को देखें',
  homeworkRevenge: 'उन ट्रेडों पर ध्यान दें जो आप नुकसान के तुरंत बाद खोलते हैं',
  homeworkDefault: 'अपने अगले सत्र से पहले अपने आँकड़ों की समीक्षा करें',
  recapMetrics: ({ n, winRate, pnl, period }) =>
    `${n} ट्रेड, ${winRate} जीत दर, ${pnl} शुद्ध ${period}।`,
  recapDefault: 'हमने आपकी आदतों और आपके वर्तमान एक्सपोज़र पर ध्यान दिया।',

  deflectionExposureFragSymbol: ({ pct, symbol }) =>
    `आपके वर्तमान खुले जोखिम का ${pct} ${symbol} में केंद्रित है`,
  deflectionExposureFragGeneric: ({ pct }) =>
    `आपके वर्तमान खुले जोखिम का ${pct} एक ही इंस्ट्रूमेंट में है`,
  deflectionExposure: ({ exposure, margin }) =>
    'मैं बाज़ार की भविष्यवाणी, कीमत का अनुमान, या खरीद/बिक्री/होल्ड की सिफ़ारिश नहीं कर सकता — यह मैं कभी नहीं करूँगा। ' +
    `लेकिन मैं आपके अपने एक्सपोज़र के बारे में सोचने में मदद कर सकता हूँ: ${exposure}, ` +
    `और आपका मार्जिन आपकी इक्विटी का ${margin} उपयोग कर रहा है। ` +
    'क्या हम बात करें कि यह आपके खाते के आकार की तुलना में कैसा बैठता है?',
  deflectionHistory: ({ period, winRate, n, pnl }) =>
    'मैं बाज़ार की भविष्यवाणी, कीमत का अनुमान, या खरीद/बिक्री/होल्ड की सिफ़ारिश नहीं कर सकता — यह मैं कभी नहीं करूँगा। ' +
    `लेकिन मैं आपके अपने इतिहास पर विचार करने में मदद कर सकता हूँ — उदाहरण के लिए, ${period} आपकी जीत दर ${winRate} थी ` +
    `${n} ट्रेडों में, और शुद्ध परिणाम ${pnl}। क्या हम देखें कि क्या काम कर रहा है और क्या नहीं?`,
  deflectionGeneric:
    'मैं बाज़ार की भविष्यवाणी, कीमत का अनुमान, या खरीद/बिक्री/होल्ड की सिफ़ारिश नहीं कर सकता — यह मैं कभी नहीं करूँगा। ' +
    'लेकिन मैं आपको आपकी अपनी पोज़िशन, जोखिम और आदतें समझने में मदद कर सकता हूँ। आप क्या देखना चाहेंगे?',

  report: {
    title: ({ period, from, to }) => `आपका ${period} सारांश (${from} → ${to})`,
    netPnl: ({ v }) => `शुद्ध लाभ/हानि: ${v}`,
    winRate: ({ v, record }) => `जीत दर: ${v} (${record})`,
    bestTrade: ({ v }) => `सबसे अच्छा ट्रेड: ${v}`,
    worstTrade: ({ v }) => `सबसे खराब ट्रेड: ${v}`,
    avgHoldDrawdown: ({ avgHold, dd, ddPct }) =>
      `औसत होल्ड: ${avgHold}  |  अधिकतम ड्रॉडाउन: ${dd} (${ddPct})`,
    openRisk: ({ n, openPnL, margin }) =>
      `खुला जोखिम: ${n} पोज़िशन, ${openPnL} अवास्तविक, मार्जिन ${margin}`,
    stoodOut: 'जो खास रहा:',
  },
};

// ── Arabic (العربية) ───────────────────────────────────────────────────────────
const ar: Strings = {
  welcome:
    '👋 مرحبًا بك في Milele Prime AI.\n\n' +
    'لربط حسابك، اضغط على زر Connect في لوحة تحكم Milele الخاصة بك.',
  chooseLanguage: '🌍 بأي لغة تود التحدث؟ اختر واحدة من الأسفل.',
  languageSet: (native) =>
    `✅ تم ضبط اللغة على ${native}. سأتحدث معك بـ${native} من الآن فصاعدًا. يمكنك تغييرها في أي وقت عبر /language.`,
  bindSuccess:
    '✅ تم الآن ربط حساب Telegram الخاص بك بحساب Milele. يمكنك أيضًا تفعيل الرسائل الصوتية والتقارير اليومية من لوحة التحكم.',
  bindAlready: '✅ حسابك مرتبط بالفعل — كل شيء جاهز.',
  bindExpired:
    '⏳ انتهت صلاحية رابط الربط هذا. يرجى فتح رابط Connect جديد من لوحة تحكم Milele.',
  bindInvalid: '⚠️ رابط الربط هذا غير صالح. يرجى استخدام زر Connect في لوحة تحكم Milele.',
  bindConflict: '⚠️ هذا الحساب مرتبط بالفعل بملف تعريف آخر. يرجى التواصل مع الدعم.',
  bindError: '⚠️ حدث خطأ ما أثناء ربط حسابك. يرجى المحاولة مرة أخرى بعد قليل.',
  accountLinked: (id) => `🔗 مرتبط بالعميل ${id}. ستتوفر ميزات الحساب في مرحلة لاحقة.`,

  unbound: 'اضغط على زر Connect في لوحة تحكم Milele لربط حسابك.',
  holding: 'أنا آخذ استراحة قصيرة — سأعود قريبًا. رسالتك محفوظة؛ راسلني مرة أخرى بعد قليل.',
  throttle: 'أمهلني لحظة — أنت ترسل أسرع مما أستطيع التفكير. سألحق بك بعد لحظة.',
  handoff:
    'شكرًا لإبلاغك بهذا — أنا أوصلك بأحد أعضاء فريق Milele الذي يمكنه مساعدتك مباشرة. سيتواصلون معك قريبًا.',
  cooldown:
    'ما زلت ألتقط أنفاسي من محادثتنا السابقة — امهلني بضع دقائق ثم راسلني مجددًا. سأكون منتعشًا وجاهزًا.',
  sttFailed: 'لم أتمكن من فهم تلك الرسالة الصوتية — هل يمكنك كتابتها بدلاً من ذلك؟',
  dataLoadFailed:
    'أواجه صعوبة في تحميل بيانات حسابك الآن — جرّب مرة أخرى بعد بضع دقائق.',

  periodDay: 'هذا اليوم',
  periodWeek: 'هذا الأسبوع',
  periodDaily: 'اليومي',
  periodWeekly: 'الأسبوعي',
  singleInstrument: 'أداة واحدة',

  lookupDrawdown: ({ period, dd, ddPct }) =>
    `أقصى تراجع لك ${period} كان ${dd} (${ddPct} من الرصيد).`,
  lookupWinRate: ({ period, winRate, wins, losses }) =>
    `نسبة فوزك ${period} هي ${winRate} — ${wins} صفقات رابحة، ${losses} خاسرة.`,
  lookupWinRateNone: ({ period }) =>
    `ليس لديك أي صفقات مغلقة ${period} بعد، لذا لا توجد نسبة فوز لعرضها.`,
  lookupTradeCount: ({ period, n }) => `أغلقت ${n} صفقة ${period}.`,
  lookupPnl: ({ period, pnl }) => `نتيجتك الصافية ${period} هي ${pnl}.`,
  lookupOpenPositions: ({ n, openPnL, margin }) =>
    `لديك حاليًا ${n} صفقة مفتوحة، ${openPnL} غير محققة، والهامش يستخدم ${margin} من حقوق الملكية.`,
  lookupBestTrade: ({ period, best }) => `أفضل صفقة لك ${period} كانت ${best}.`,
  lookupWorstTrade: ({ period, worst }) => `أسوأ صفقة لك ${period} كانت ${worst}.`,
  lookupExposure: ({ pct, symbol }) => `${pct} من انكشافك المفتوح في ${symbol}.`,
  lookupExposureNone: 'ليس لديك أي صفقات مفتوحة حاليًا.',

  exitV0:
    'عليّ العودة لمتابعة الرسوم البيانية — لكن فكّر فيما تحدثنا عنه. راسلني في أي وقت.',
  exitV1: ({ homework }) =>
    `الأسواق لا تنام، لذا أعود إلى الشاشات. الواجب: ${homework}. نتحدث قريبًا.`,
  exitV2: ({ recap }) => `سأبتعد قليلاً لأبقى على اطلاع. خلاصة سريعة: ${recap} سأكون موجودًا لاحقًا.`,
  homeworkWeekend: 'راجع كيف يؤثر الاحتفاظ بالصفقات خلال عطلة نهاية الأسبوع على نتائجك',
  homeworkOverleverage: 'انظر إلى استخدامك للهامش مقارنة بحجم حسابك',
  homeworkRevenge: 'انتبه إلى الصفقات التي تفتحها مباشرة بعد الخسارة',
  homeworkDefault: 'راجع أرقامك الخاصة قبل جلستك القادمة',
  recapMetrics: ({ n, winRate, pnl, period }) =>
    `${n} صفقات، نسبة فوز ${winRate}، ${pnl} صافي ${period}.`,
  recapDefault: 'ركّزنا على عاداتك وانكشافك الحالي.',

  deflectionExposureFragSymbol: ({ pct, symbol }) =>
    `${pct} من مخاطرك المفتوحة الحالية مُركّزة في ${symbol}`,
  deflectionExposureFragGeneric: ({ pct }) =>
    `${pct} من مخاطرك المفتوحة الحالية في أداة واحدة`,
  deflectionExposure: ({ exposure, margin }) =>
    'لا أستطيع تقديم توقعات للسوق أو توقعات للأسعار أو توصيات بالشراء/البيع/الاحتفاظ — وهذا شيء لن أفعله أبدًا. ' +
    `لكن ما يمكنني فعله هو مساعدتك على التفكير في انكشافك الخاص: ${exposure}، ` +
    `والهامش لديك يستخدم ${margin} من حقوق ملكيتك. ` +
    'هل تود أن نناقش كيف يتناسب ذلك مع حجم حسابك؟',
  deflectionHistory: ({ period, winRate, n, pnl }) =>
    'لا أستطيع تقديم توقعات للسوق أو توقعات للأسعار أو توصيات بالشراء/البيع/الاحتفاظ — وهذا شيء لن أفعله أبدًا. ' +
    `لكن ما يمكنني فعله هو مساعدتك على التأمل في سجلك الخاص — على سبيل المثال، نسبة فوزك ${period} كانت ${winRate} ` +
    `عبر ${n} صفقات، بنتيجة صافية ${pnl}. هل نتعمق فيما ينجح وما لا ينجح؟`,
  deflectionGeneric:
    'لا أستطيع تقديم توقعات للسوق أو توقعات للأسعار أو توصيات بالشراء/البيع/الاحتفاظ — وهذا شيء لن أفعله أبدًا. ' +
    'لكن ما يمكنني فعله هو مساعدتك على فهم صفقاتك ومخاطرك وعاداتك. ماذا تود أن نستعرض؟',

  report: {
    title: ({ period, from, to }) => `ملخصك ${period} (${from} → ${to})`,
    netPnl: ({ v }) => `صافي الربح/الخسارة: ${v}`,
    winRate: ({ v, record }) => `نسبة الفوز: ${v} (${record})`,
    bestTrade: ({ v }) => `أفضل صفقة: ${v}`,
    worstTrade: ({ v }) => `أسوأ صفقة: ${v}`,
    avgHoldDrawdown: ({ avgHold, dd, ddPct }) =>
      `متوسط مدة الاحتفاظ: ${avgHold}  |  أقصى تراجع: ${dd} (${ddPct})`,
    openRisk: ({ n, openPnL, margin }) =>
      `المخاطر المفتوحة: ${n} صفقة، ${openPnL} غير محققة، الهامش ${margin}`,
    stoodOut: 'ما لفت الانتباه:',
  },
};

// ── French (Français) ──────────────────────────────────────────────────────────
const fr: Strings = {
  welcome:
    '👋 Bienvenue sur Milele Prime AI.\n\n' +
    'Pour lier votre compte, appuyez sur le bouton Connect dans votre tableau de bord Milele.',
  chooseLanguage: '🌍 Dans quelle langue souhaitez-vous discuter ? Choisissez-en une ci-dessous.',
  languageSet: (native) =>
    `✅ Langue définie sur ${native}. Je discuterai désormais avec vous en ${native}. Vous pouvez la changer à tout moment avec /language.`,
  bindSuccess:
    '✅ Votre Telegram est maintenant lié à votre compte Milele. Vous pouvez aussi activer la voix et les rapports quotidiens depuis votre tableau de bord.',
  bindAlready: '✅ Votre compte est déjà lié — tout est prêt.',
  bindExpired:
    '⏳ Ce lien de connexion a expiré. Veuillez ouvrir un nouveau lien Connect depuis votre tableau de bord Milele.',
  bindInvalid: '⚠️ Ce lien de connexion est invalide. Veuillez utiliser le bouton Connect dans votre tableau de bord Milele.',
  bindConflict: '⚠️ Ce compte est déjà lié à un autre profil. Veuillez contacter le support.',
  bindError: '⚠️ Une erreur est survenue lors de la liaison de votre compte. Veuillez réessayer sous peu.',
  accountLinked: (id) => `🔗 Lié au client ${id}. Les fonctionnalités du compte arriveront dans une phase ultérieure.`,

  unbound: 'Appuyez sur le bouton Connect dans votre tableau de bord Milele pour lier votre compte.',
  holding: 'Je fais une petite pause — de retour bientôt. Votre message est en sécurité ; réécrivez-moi dans un instant.',
  throttle: 'Un instant — vous écrivez plus vite que je ne peux réfléchir. Je vous rattrape tout de suite.',
  handoff:
    "Merci de l'avoir signalé — je vous mets en relation avec un membre de l'équipe Milele qui pourra vous aider directement. Il vous recontactera sous peu.",
  cooldown:
    'Je reprends encore mon souffle après notre dernière discussion — laissez-moi quelques minutes puis réécrivez-moi. Je serai frais et prêt.',
  sttFailed: "Je n'ai pas bien saisi ce message vocal — pourriez-vous l'écrire à la place ?",
  dataLoadFailed:
    "J'ai du mal à charger les données de votre compte pour le moment — réessayez dans quelques minutes.",

  periodDay: 'ce jour',
  periodWeek: 'cette semaine',
  periodDaily: 'quotidien',
  periodWeekly: 'hebdomadaire',
  singleInstrument: 'un seul instrument',

  lookupDrawdown: ({ period, dd, ddPct }) =>
    `Votre drawdown maximal ${period} était de ${dd} (${ddPct} du solde).`,
  lookupWinRate: ({ period, winRate, wins, losses }) =>
    `Votre taux de réussite ${period} est de ${winRate} — ${wins} gains, ${losses} pertes.`,
  lookupWinRateNone: ({ period }) =>
    `Vous n'avez encore aucune position clôturée ${period}, il n'y a donc pas de taux de réussite à indiquer.`,
  lookupTradeCount: ({ period, n }) =>
    `Vous avez clôturé ${n} ${n === 1 ? 'position' : 'positions'} ${period}.`,
  lookupPnl: ({ period, pnl }) => `Votre résultat net ${period} est de ${pnl}.`,
  lookupOpenPositions: ({ n, openPnL, margin }) =>
    `Vous avez actuellement ${n} ${n === 1 ? 'position ouverte' : 'positions ouvertes'}, ${openPnL} non réalisé, avec une marge à ${margin} des fonds propres.`,
  lookupBestTrade: ({ period, best }) => `Votre meilleure position ${period} était ${best}.`,
  lookupWorstTrade: ({ period, worst }) => `Votre pire position ${period} était ${worst}.`,
  lookupExposure: ({ pct, symbol }) => `${pct} de votre exposition ouverte est sur ${symbol}.`,
  lookupExposureNone: "Vous n'avez aucune position ouverte pour le moment.",

  exitV0:
    'Je dois retourner surveiller les graphiques — mais réfléchissez à ce que nous avons vu. Écrivez-moi quand vous voulez.',
  exitV1: ({ homework }) =>
    `Les marchés ne dorment pas, je retourne aux écrans. Devoir : ${homework}. À bientôt.`,
  exitV2: ({ recap }) => `Je m'absente pour garder un œil sur tout. Petit récap : ${recap} Je reste disponible plus tard.`,
  homeworkWeekend: 'examinez comment vos positions gardées le week-end affectent vos résultats',
  homeworkOverleverage: "regardez votre utilisation de la marge par rapport à la taille de votre compte",
  homeworkRevenge: 'remarquez les positions que vous ouvrez juste après une perte',
  homeworkDefault: 'passez en revue vos propres chiffres avant votre prochaine session',
  recapMetrics: ({ n, winRate, pnl, period }) =>
    `${n} positions, ${winRate} de taux de réussite, ${pnl} net ${period}.`,
  recapDefault: 'nous nous sommes concentrés sur vos habitudes et votre exposition actuelle.',

  deflectionExposureFragSymbol: ({ pct, symbol }) =>
    `${pct} de votre risque ouvert actuel est concentré sur ${symbol}`,
  deflectionExposureFragGeneric: ({ pct }) =>
    `${pct} de votre risque ouvert actuel repose sur un seul instrument`,
  deflectionExposure: ({ exposure, margin }) =>
    "Je ne peux pas faire de prévisions de marché, de prévisions de prix ni de recommandations d'achat/vente/conservation — je ne le ferai jamais. " +
    `En revanche, je peux vous aider à réfléchir à votre propre exposition : ${exposure}, ` +
    `et votre marge utilise ${margin} de vos fonds propres. ` +
    'Voulez-vous que nous voyions comment cela se situe par rapport à la taille de votre compte ?',
  deflectionHistory: ({ period, winRate, n, pnl }) =>
    "Je ne peux pas faire de prévisions de marché, de prévisions de prix ni de recommandations d'achat/vente/conservation — je ne le ferai jamais. " +
    `En revanche, je peux vous aider à réfléchir à votre propre historique — par exemple, votre taux de réussite ${period} était de ${winRate} ` +
    `sur ${n} positions, avec un résultat net de ${pnl}. Voulez-vous creuser ce qui fonctionne et ce qui ne fonctionne pas ?`,
  deflectionGeneric:
    "Je ne peux pas faire de prévisions de marché, de prévisions de prix ni de recommandations d'achat/vente/conservation — je ne le ferai jamais. " +
    'En revanche, je peux vous aider à comprendre vos propres positions, votre risque et vos habitudes. Que souhaitez-vous examiner ?',

  report: {
    title: ({ period, from, to }) => `Votre résumé ${period} (${from} → ${to})`,
    netPnl: ({ v }) => `P&L net : ${v}`,
    winRate: ({ v, record }) => `Taux de réussite : ${v} (${record})`,
    bestTrade: ({ v }) => `Meilleure position : ${v}`,
    worstTrade: ({ v }) => `Pire position : ${v}`,
    avgHoldDrawdown: ({ avgHold, dd, ddPct }) =>
      `Durée moy. de détention : ${avgHold}  |  Drawdown max : ${dd} (${ddPct})`,
    openRisk: ({ n, openPnL, margin }) =>
      `Risque ouvert : ${n} position(s), ${openPnL} non réalisé, marge ${margin}`,
    stoodOut: 'Ce qui ressort :',
  },
};

// ── Spanish (Español) ──────────────────────────────────────────────────────────
const es: Strings = {
  welcome:
    '👋 Bienvenido a Milele Prime AI.\n\n' +
    'Para vincular tu cuenta, pulsa el botón Connect en tu panel de Milele.',
  chooseLanguage: '🌍 ¿En qué idioma te gustaría chatear? Elige uno abajo.',
  languageSet: (native) =>
    `✅ Idioma establecido en ${native}. A partir de ahora chatearé contigo en ${native}. Puedes cambiarlo cuando quieras con /language.`,
  bindSuccess:
    '✅ Tu Telegram ya está vinculado a tu cuenta de Milele. También puedes activar la voz y los informes diarios desde tu panel.',
  bindAlready: '✅ Tu cuenta ya está vinculada — todo listo.',
  bindExpired:
    '⏳ Ese enlace de conexión ha caducado. Abre un nuevo enlace Connect desde tu panel de Milele.',
  bindInvalid: '⚠️ Ese enlace de conexión no es válido. Usa el botón Connect en tu panel de Milele.',
  bindConflict: '⚠️ Esta cuenta ya está vinculada a otro perfil. Ponte en contacto con soporte.',
  bindError: '⚠️ Algo salió mal al vincular tu cuenta. Inténtalo de nuevo en breve.',
  accountLinked: (id) => `🔗 Vinculado al cliente ${id}. Las funciones de la cuenta llegarán en una fase posterior.`,

  unbound: 'Pulsa el botón Connect en tu panel de Milele para vincular tu cuenta.',
  holding: 'Estoy tomando un breve descanso — vuelvo enseguida. Tu mensaje está a salvo; escríbeme de nuevo en un rato.',
  throttle: 'Dame un segundo — estás enviando más rápido de lo que puedo pensar. Te alcanzo en un momento.',
  handoff:
    'Gracias por avisar — te estoy poniendo en contacto con un miembro del equipo de Milele que puede ayudarte directamente. Se comunicarán contigo en breve.',
  cooldown:
    'Todavía estoy recuperando el aliento de nuestra última charla — dame unos minutos y escríbeme de nuevo. Estaré fresco y listo.',
  sttFailed: 'No pude entender ese mensaje de voz — ¿te importaría escribirlo?',
  dataLoadFailed:
    'Estoy teniendo problemas para cargar los datos de tu cuenta ahora mismo — inténtalo de nuevo en unos minutos.',

  periodDay: 'este día',
  periodWeek: 'esta semana',
  periodDaily: 'diario',
  periodWeekly: 'semanal',
  singleInstrument: 'un solo instrumento',

  lookupDrawdown: ({ period, dd, ddPct }) =>
    `Tu drawdown máximo ${period} fue de ${dd} (${ddPct} del saldo).`,
  lookupWinRate: ({ period, winRate, wins, losses }) =>
    `Tu tasa de acierto ${period} es ${winRate} — ${wins} ganadas, ${losses} perdidas.`,
  lookupWinRateNone: ({ period }) =>
    `Aún no tienes operaciones cerradas ${period}, así que no hay tasa de acierto que mostrar.`,
  lookupTradeCount: ({ period, n }) =>
    `Cerraste ${n} ${n === 1 ? 'operación' : 'operaciones'} ${period}.`,
  lookupPnl: ({ period, pnl }) => `Tu resultado neto ${period} es ${pnl}.`,
  lookupOpenPositions: ({ n, openPnL, margin }) =>
    `Actualmente tienes ${n} ${n === 1 ? 'posición abierta' : 'posiciones abiertas'}, ${openPnL} no realizado, con el margen al ${margin} del capital.`,
  lookupBestTrade: ({ period, best }) => `Tu mejor operación ${period} fue ${best}.`,
  lookupWorstTrade: ({ period, worst }) => `Tu peor operación ${period} fue ${worst}.`,
  lookupExposure: ({ pct, symbol }) => `El ${pct} de tu exposición abierta está en ${symbol}.`,
  lookupExposureNone: 'No tienes posiciones abiertas en este momento.',

  exitV0:
    'Tengo que volver a vigilar los gráficos — pero piensa en lo que vimos. Escríbeme cuando quieras.',
  exitV1: ({ homework }) =>
    `Los mercados no duermen, así que vuelvo a las pantallas. Tarea: ${homework}. Hablamos pronto.`,
  exitV2: ({ recap }) => `Me aparto un momento para estar atento. Resumen rápido: ${recap} Estaré por aquí más tarde.`,
  homeworkWeekend: 'revisa cómo afectan a tus resultados las posiciones que mantienes el fin de semana',
  homeworkOverleverage: 'mira tu uso del margen en relación con el tamaño de tu cuenta',
  homeworkRevenge: 'fíjate en las operaciones que abres justo después de una pérdida',
  homeworkDefault: 'revisa tus propios números antes de tu próxima sesión',
  recapMetrics: ({ n, winRate, pnl, period }) =>
    `${n} operaciones, ${winRate} de acierto, ${pnl} neto ${period}.`,
  recapDefault: 'nos centramos en tus hábitos y tu exposición actual.',

  deflectionExposureFragSymbol: ({ pct, symbol }) =>
    `el ${pct} de tu riesgo abierto actual está concentrado en ${symbol}`,
  deflectionExposureFragGeneric: ({ pct }) =>
    `el ${pct} de tu riesgo abierto actual está en un solo instrumento`,
  deflectionExposure: ({ exposure, margin }) =>
    'No puedo hacer pronósticos de mercado, predicciones de precios ni recomendaciones de comprar/vender/mantener — eso no lo haré nunca. ' +
    `Lo que sí puedo hacer es ayudarte a pensar en tu propia exposición: ${exposure}, ` +
    `y tu margen está usando el ${margin} de tu capital. ` +
    '¿Quieres que hablemos de cómo encaja eso con el tamaño de tu cuenta?',
  deflectionHistory: ({ period, winRate, n, pnl }) =>
    'No puedo hacer pronósticos de mercado, predicciones de precios ni recomendaciones de comprar/vender/mantener — eso no lo haré nunca. ' +
    `Lo que sí puedo hacer es ayudarte a reflexionar sobre tu propio historial — por ejemplo, tu tasa de acierto ${period} fue ${winRate} ` +
    `en ${n} operaciones, con un resultado neto de ${pnl}. ¿Quieres que analicemos qué funciona y qué no?`,
  deflectionGeneric:
    'No puedo hacer pronósticos de mercado, predicciones de precios ni recomendaciones de comprar/vender/mantener — eso no lo haré nunca. ' +
    'Lo que sí puedo hacer es ayudarte a entender tus propias posiciones, tu riesgo y tus hábitos. ¿Qué te gustaría revisar?',

  report: {
    title: ({ period, from, to }) => `Tu resumen ${period} (${from} → ${to})`,
    netPnl: ({ v }) => `P&L neto: ${v}`,
    winRate: ({ v, record }) => `Tasa de acierto: ${v} (${record})`,
    bestTrade: ({ v }) => `Mejor operación: ${v}`,
    worstTrade: ({ v }) => `Peor operación: ${v}`,
    avgHoldDrawdown: ({ avgHold, dd, ddPct }) =>
      `Retención media: ${avgHold}  |  Drawdown máx.: ${dd} (${ddPct})`,
    openRisk: ({ n, openPnL, margin }) =>
      `Riesgo abierto: ${n} posición(es), ${openPnL} no realizado, margen ${margin}`,
    stoodOut: 'Lo que destacó:',
  },
};

// ── Portuguese (Português) ──────────────────────────────────────────────────────
const pt: Strings = {
  welcome:
    '👋 Bem-vindo ao Milele Prime AI.\n\n' +
    'Para vincular a sua conta, toque no botão Connect no seu painel Milele.',
  chooseLanguage: '🌍 Em que idioma gostaria de conversar? Escolha um abaixo.',
  languageSet: (native) =>
    `✅ Idioma definido para ${native}. A partir de agora vou conversar com você em ${native}. Você pode mudar a qualquer momento com /language.`,
  bindSuccess:
    '✅ O seu Telegram agora está vinculado à sua conta Milele. Você também pode ativar voz e relatórios diários no seu painel.',
  bindAlready: '✅ A sua conta já está vinculada — tudo pronto.',
  bindExpired:
    '⏳ Esse link de conexão expirou. Abra um novo link Connect no seu painel Milele.',
  bindInvalid: '⚠️ Esse link de conexão é inválido. Use o botão Connect no seu painel Milele.',
  bindConflict: '⚠️ Esta conta já está vinculada a outro perfil. Entre em contato com o suporte.',
  bindError: '⚠️ Algo deu errado ao vincular a sua conta. Tente novamente em breve.',
  accountLinked: (id) => `🔗 Vinculado ao cliente ${id}. Os recursos da conta chegarão em uma fase posterior.`,

  unbound: 'Toque no botão Connect no seu painel Milele para vincular a sua conta.',
  holding: 'Estou fazendo uma pausa rápida — volto já. A sua mensagem está segura; escreva-me de novo daqui a pouco.',
  throttle: 'Só um segundo — você está enviando mais rápido do que consigo pensar. Já te alcanço.',
  handoff:
    'Obrigado por avisar — estou te conectando com um membro da equipe Milele que pode ajudá-lo diretamente. Eles entrarão em contato em breve.',
  cooldown:
    'Ainda estou recuperando o fôlego da nossa última conversa — me dê alguns minutos e escreva de novo. Estarei renovado e pronto.',
  sttFailed: 'Não consegui entender essa mensagem de voz — poderia digitá-la?',
  dataLoadFailed:
    'Estou com dificuldade para carregar os dados da sua conta agora — tente novamente em alguns minutos.',

  periodDay: 'este dia',
  periodWeek: 'esta semana',
  periodDaily: 'diário',
  periodWeekly: 'semanal',
  singleInstrument: 'um único instrumento',

  lookupDrawdown: ({ period, dd, ddPct }) =>
    `O seu drawdown máximo ${period} foi de ${dd} (${ddPct} do saldo).`,
  lookupWinRate: ({ period, winRate, wins, losses }) =>
    `A sua taxa de acerto ${period} é ${winRate} — ${wins} ganhos, ${losses} perdas.`,
  lookupWinRateNone: ({ period }) =>
    `Você ainda não tem operações fechadas ${period}, então não há taxa de acerto a mostrar.`,
  lookupTradeCount: ({ period, n }) =>
    `Você fechou ${n} ${n === 1 ? 'operação' : 'operações'} ${period}.`,
  lookupPnl: ({ period, pnl }) => `O seu resultado líquido ${period} é ${pnl}.`,
  lookupOpenPositions: ({ n, openPnL, margin }) =>
    `Atualmente você tem ${n} ${n === 1 ? 'posição aberta' : 'posições abertas'}, ${openPnL} não realizado, com a margem em ${margin} do patrimônio.`,
  lookupBestTrade: ({ period, best }) => `A sua melhor operação ${period} foi ${best}.`,
  lookupWorstTrade: ({ period, worst }) => `A sua pior operação ${period} foi ${worst}.`,
  lookupExposure: ({ pct, symbol }) => `${pct} da sua exposição aberta está em ${symbol}.`,
  lookupExposureNone: 'Você não tem posições abertas no momento.',

  exitV0:
    'Preciso voltar a acompanhar os gráficos — mas pense no que conversamos. Escreva-me quando quiser.',
  exitV1: ({ homework }) =>
    `Os mercados não dormem, então volto às telas. Tarefa: ${homework}. Falamos em breve.`,
  exitV2: ({ recap }) => `Vou me afastar um pouco para ficar de olho. Resumo rápido: ${recap} Estarei por aqui mais tarde.`,
  homeworkWeekend: 'reveja como manter posições no fim de semana está afetando os seus resultados',
  homeworkOverleverage: 'observe o seu uso de margem em relação ao tamanho da sua conta',
  homeworkRevenge: 'repare nas operações que você abre logo após uma perda',
  homeworkDefault: 'revise os seus próprios números antes da sua próxima sessão',
  recapMetrics: ({ n, winRate, pnl, period }) =>
    `${n} operações, ${winRate} de acerto, ${pnl} líquido ${period}.`,
  recapDefault: 'focamos nos seus hábitos e na sua exposição atual.',

  deflectionExposureFragSymbol: ({ pct, symbol }) =>
    `${pct} do seu risco aberto atual está concentrado em ${symbol}`,
  deflectionExposureFragGeneric: ({ pct }) =>
    `${pct} do seu risco aberto atual está em um único instrumento`,
  deflectionExposure: ({ exposure, margin }) =>
    'Não posso fazer previsões de mercado, previsões de preços nem recomendações de compra/venda/manutenção — isso é algo que nunca farei. ' +
    `O que eu posso fazer é ajudá-lo a pensar na sua própria exposição: ${exposure}, ` +
    `e a sua margem está usando ${margin} do seu patrimônio. ` +
    'Quer conversar sobre como isso se compara ao tamanho da sua conta?',
  deflectionHistory: ({ period, winRate, n, pnl }) =>
    'Não posso fazer previsões de mercado, previsões de preços nem recomendações de compra/venda/manutenção — isso é algo que nunca farei. ' +
    `O que eu posso fazer é ajudá-lo a refletir sobre o seu próprio histórico — por exemplo, a sua taxa de acerto ${period} foi ${winRate} ` +
    `em ${n} operações, com um resultado líquido de ${pnl}. Quer analisar o que está funcionando e o que não está?`,
  deflectionGeneric:
    'Não posso fazer previsões de mercado, previsões de preços nem recomendações de compra/venda/manutenção — isso é algo que nunca farei. ' +
    'O que eu posso fazer é ajudá-lo a entender as suas próprias posições, o seu risco e os seus hábitos. O que gostaria de ver?',

  report: {
    title: ({ period, from, to }) => `O seu resumo ${period} (${from} → ${to})`,
    netPnl: ({ v }) => `P&L líquido: ${v}`,
    winRate: ({ v, record }) => `Taxa de acerto: ${v} (${record})`,
    bestTrade: ({ v }) => `Melhor operação: ${v}`,
    worstTrade: ({ v }) => `Pior operação: ${v}`,
    avgHoldDrawdown: ({ avgHold, dd, ddPct }) =>
      `Retenção média: ${avgHold}  |  Drawdown máx.: ${dd} (${ddPct})`,
    openRisk: ({ n, openPnL, margin }) =>
      `Risco aberto: ${n} posição(ões), ${openPnL} não realizado, margem ${margin}`,
    stoodOut: 'O que se destacou:',
  },
};

/** The full catalog, keyed by language code. */
export const CATALOG: Readonly<Record<Language, Strings>> = { en, ur, hi, ar, fr, es, pt };
